Url Shortener/url_shortener/models.py
import string
from datetime import datetime
from random import choices
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin

db = SQLAlchemy()

class Link(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    original_url = db.Column(db.String(512))
    short_url = db.Column(db.String(20), unique=True)
    visits = db.Column(db.Integer, default=0)
    date_created = db.Column(db.DateTime, default=datetime.now)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.short_url = self.generate_short_link()

    def generate_short_link(self):
        characters = string.digits + string.ascii_letters
        short_url = ''.join(choices(characters, k=3))

        link = self.query.filter_by(short_url=short_url).first()

        if link:
            return self.generate_short_link()
        
        return short_url
    

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    links = db.relationship('Link')

Url Shortener/url_shortener/__init__.py
from flask import Flask, app

from .api import initialize_routes
from .models import db, User
from .routes import views
from .auth import auth
from flask_restful import Api

def create_app(config_file='settings.py'):
    app = Flask(__name__)
    api =   Api(app)
    app.config.from_pyfile(config_file)
    app.secret_key = 'development'

    db.init_app(app)

    app.register_blueprint(views)
    app.register_blueprint(auth)
    from flask_login import LoginManager
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    initialize_routes(api)

    return app

Url Shortener/url_shortener/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from werkzeug.security import check_password_hash, generate_password_hash
from .models import db
from flask_login import login_user, login_required, logout_user, current_user


from .models import User, Link

auth = Blueprint('auth', __name__)

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        email = request.form.get('email')
        name = request.form.get('name')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        user = User.query.filter_by(email=email).first()
        if user:
            message=['Email already exists.', 'error']
            return render_template("register.html", message=message)
        elif len(email) < 4:
            message=['Email must be greater than 3 characters.', 'error']
            return render_template("register.html", message=message)
        elif len(name) < 2:
            message=['First name must be greater than 1 character.', 'error']
            return render_template("register.html", message=message)
        elif password1 != password2:
            message=['Passwords don\'t match.', 'error']
            return render_template("register.html", message=message)
        elif len(password1) < 7:
            message=['Password must be at least 7 characters.', 'error']
            return render_template("register.html", message=message)
        else:
            new_user = User(email=email, first_name=name, password=password1)
            db.session.add(new_user)
            db.session.commit()
            flash('Account created!', category='success')
            print("Account created!") 
            return redirect(url_for('auth.login'))
    return render_template("register.html", message="None")


@auth.route('/login', methods=['GET', 'POST'])
def login():
    
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if user:
            if user.password == password:
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.add'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.index'))

Url Shortener/url_shortener/routes.py
import re
from flask import Blueprint, render_template,redirect,Response,request,url_for
from flask.helpers import flash
from .models import db
from flask_login import login_user, login_required, logout_user, current_user
from .models import Link,User,Subscription
import requests
views = Blueprint('views', __name__)

@views.route('/')
def index():
    return render_template('index.html',user=current_user) 


@views.route('/<short_url>')
def redirect_to_url(short_url):
    link = Link.query.filter_by(short_url=short_url).first_or_404()

    link.visits = link.visits + 1
    db.session.commit()

    r = requests.get(link.original_url)
    return Response(r, mimetype='text/xml')


@views.route('/add', methods = ['GET','POST'])
@login_required
def add():
    user_plan = User.query.filter_by(id=current_user.id).first()
    sub_plan = Subscription.query.filter_by(sub_id=user_plan.plan_id).first()
    sub_maxurls = sub_plan.max_urls
    sub_maxfeeds = sub_plan.max_feeds
    links = Link.query.filter_by(user_id=current_user.id).limit(sub_maxfeeds).all()
    
    if request.method == 'POST':
        full_url = request.form.getlist('field[]')
        n = request.form['limit']
        print(len(full_url))
        if len(full_url)<=0:
            flash('Input field cannot be empty', category='error')
            return render_template('url_add.html',sub_maxfeeds=sub_maxfeeds,sub_maxurls=sub_maxurls,user=current_user,links=links)
        i = 1
        #str = 'http://127.0.0.1:8000/rss?f='
        str = 'https://feed-mixer.herokuapp.com/rss?f='
        for value in full_url:
            if value != '':
                if i == 1:
                    str += value 
                    i += 1
                    str1 = value
                else:
                    str +='&f=' + value
                    i += 1
            else:
                flash('Input field cannot be empty', category='error')
                return render_template('url_add.html',user=current_user,links=links,sub_maxfeeds=sub_maxfeeds,sub_maxurls=sub_maxurls)
        if n:
            if n.isdigit():
                str += '&n=' + n
            else:
                flash('Feeds per URL should be integer', category='error')
                return render_template('url_add.html',user=current_user,links=links,sub_maxfeeds=sub_maxfeeds,sub_maxurls=sub_maxurls) 
        if len(links) >= sub_maxfeeds:
            flash('Feed are Maxed out!', category='error')
            return render_template('url_add.html',user=current_user,links=links,sub_maxfeeds=sub_maxfeeds,sub_maxurls=sub_maxurls)
        link = Link(original_url=str, user_id=current_user.id)
        db.session.add(link)
        db.session.commit()
        result = Link.query.filter_by(original_url=str).first_or_404()
        links = Link.query.filter_by(user_id=current_user.id).limit(sub_maxfeeds).all()
        
        return render_template('link_added.html',original_url=result.original_url,new_link=result.short_url,user=current_user,sub_maxfeeds=sub_maxfeeds,sub_maxurls=sub_maxurls)
    links = Link.query.filter_by(user_id=current_user.id).limit(sub_maxfeeds).all()
    return render_template('url_add.html',user=current_user,links=links,sub_maxfeeds=sub_maxfeeds,sub_maxurls=sub_maxurls)


@views.route('/dellink', methods = ['GET','POST'])
def dellink():
  if request.method == 'POST':
    link = request.form['linkid']
    Cust_id = Link.query.get(link)
    db.session.delete(Cust_id)
    db.session.commit()
    return redirect('/add')




@views.route('/profile', methods = ['GET','POST'])
def profile():
    plan = Subscription.query.filter_by(sub_id = current_user.plan_id).first()
    if request.method == 'POST':
        options = request.form['options']
        user_plan = Subscription.query.filter_by(name=str(options)).first()
        current_user.plan_id = user_plan.sub_id
        db.session.commit()
        return redirect(url_for('views.profile'))
    return render_template('profile.html',user=current_user,plan=plan.name)

Url Shortener/url_shortener/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" 
    crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" 
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" 
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" 
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script> 

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">


  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='bootstrap/css/bootstrap-icons.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='bootstrap/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='bootstrap/css/quill.snow.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='bootstrap/css/quill.bubble.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='bootstrap/css/remixicon.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='bootstrap/css/simple-datatables/style.css') }}" rel="stylesheet">
  
  <!-- Template Main CSS File -->
  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">


    <title>{% block title %}Home{% endblock %}</title>
  </head>

   <body>
     {% block body %} {% endblock %}
     <div class="container">{% block content %} {% endblock %}</div>
      
     {% block footer %} {% endblock %}

        <script src="{{ url_for('static', filename='bootstrap/js/bootrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='bootstrap/js/simple-datatables.js') }}"></script>
        <script src="{{ url_for('static', filename='bootstrap/js/validate.js') }}"></script>
        <script src="{{ url_for('static', filename='bootsrap/js/jquery-slim.min.js') }}"></script>
        <script src="{{ url_for('static', filename='bootstrap/js/popper.min.js') }}"></script>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

        <!-- Template Main JS File -->
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>

    </body>
</html>

Url Shortener/url_shortener/templates/index.html
{% extends "base.html" %}

{% block body %}
  <nav class="navbar navbar-expand-lg navbar-light rounded mb-5 py-4" style="background-color: white; font-size: large; opacity: 1; box-shadow: 0px 0px 15px 0px rgba(1, 41, 112, 0.1);">
      <a class="navbar-brand" href="#"><div class="d-flex align-items-center">
        <a href="/" class="logo d-flex ">
         <div class="icon">
          <i class="fa fa-rss fa-lg mx-1 mt-1" style="color: rgba(12, 12, 105, 0.932);"></i>
         </div>
         
          <span>RSS FeedMixer</span>
        </a>
      </div></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse align-items-center me-5 pe-5" id="navbarsExample09">
        <ul class="navbar-nav mr-auto">
          
        </ul>
      </ul>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="/add">{{user.first_name}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/logout">Logout</a>
        </li>
        {% else %}
          <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
          </li>
          <li class="nav-item ">
              <a class="nav-link" href="/register">Register</a>
          </li>
          {% endif %}
      </ul>
      </div>
    </nav>
{% endblock %}

{% block content %}


    <!-- <div class="pagetitle">
      <h1>Blank Page</h1>
    
    </div>End Page Title -->

    <section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <p class="card-title" style="font-size: 1.5rem;">What is a RSS Feed Mixer?</p>
              <ul style="list-style:none; font-size: large;">
                <li class="mb-2"><i class="fa fa-check-circle me-2"></i>An RSS feed is a file that contains a summary of updates from a website, often in the form of a list of articles with links.</li>
                <li class="mb-2"><i class="fa fa-check-circle me-2"></i>RSS is used by people to stay informed about news, podcasts, and other information online.</li>
                <li><i class="fa fa-check-circle me-2"></i>RSS Feed Mixer can be used to mix multiple RSS Feeds and get feeds on topics of your interest.</li>
              </ul>
              <p class="card-title" style="font-size: 1.5rem;">How to use RSS Feed Mixer?</p>
              <ul style="list-style:none; font-size: large;">
                <li class="mb-2"><i class="fa fa-check-circle me-2"></i>Enter the URL address of each feed.</li>
                <li class="mb-2"><i class="fa fa-check-circle me-2"></i>Press Add button to add multiple feeds.</li>
                <li class="mb-2"><i class="fa fa-check-circle me-2"></i>Enter feed per url to limit feeds per url.</li>
                <li class="mb-2"><i class="fa fa-check-circle me-2"></i>Press Submit to create your personal RSS feed.</li>
              </ul>
            </div>
          </div>

        </div>

      </div>

      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <p class="card-title" style="font-size: 1.5rem;">Get your feed mixed here!</p>
              <div class=" text-center">
                <h4 class="mb-3">Are you new here?</h4>
                <h5>Please register here <a href="/register" class="btn btn-primary mx-3">REGISTER<i class="fa fa-user-plus ms-2"></i></a></h5>
              </div>
              <div class=" text-center mt-5">
                <h4 class="mb-3">If you already have an account</h4>
                <h5>Login here<a href="/login" class="btn btn-primary mx-3">LOGIN<i class="fa fa-sign-in ms-2"></i></a></h5>
              </div>
              <div class=" text-center mt-5">
                <h4 class="mb-3">Get your feedmix</h4>
                <h5><a href="/add" class="btn btn-primary mx-3">Feedmix<i class="fa fa-rss-square ms-2"></i></a></h5>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section>
    
  

  {% endblock %}

  {% block footer %}
  <footer class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>RSS FeedMixer</span></strong>. All Rights Reserved
    </div>
  </footer><!-- End Footer -->
  {% endblock %}

Url Shortener/url_shortener/templates/link_added.html
{% extends "base.html" %}

{% block body %}
  <nav class="navbar navbar-expand-lg navbar-light rounded mb-5 py-4" style="background-color: white; font-size: large; opacity: 1; box-shadow: 0px 0px 15px 0px rgba(1, 41, 112, 0.1);">
      <a class="navbar-brand" href="#"><div class="d-flex align-items-center">
        <a href="/" class="logo d-flex ">
         <div class="icon">
          <i class="fa fa-rss fa-lg mx-1 mt-1" style="color: rgba(12, 12, 105, 0.932);"></i>
         </div>
         
          <span>RSS FeedMixer</span>
        </a>
      </div></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse align-items-center me-5 pe-5" id="navbarsExample09">
        <ul class="navbar-nav mr-auto">
          
        </ul>
    </ul>
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="/add">{{user.first_name}}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/logout">Logout</a>
      </li>
      {% else %}
        <li class="nav-item">
            <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="/register">Register</a>
        </li>
        {% endif %}
    </ul>
      </div>
    </nav>
{% endblock %}

{% block content %}


    <!-- <div class="pagetitle">
      <h1>Blank Page</h1>
    
    </div>End Page Title -->

    <section class="section">
    

      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h3 class="card-title" style="font-size: larger;">Your feed mix URLs.</h3>
              <div class="mx-5" style="color:blue;">
               <div class="mb-2"> Full URL : {{original_url}}</div>
               <div class="mb-4"> Short URL : {{url_for('views.redirect_to_url',short_url=new_link, _external=True)}}</div>
               <a class="btn btn-primary" href="{{url_for('views.redirect_to_url',short_url=new_link, _external=True)}}">View FeedMix</a>
              </div>
              
            </div>
          </div>

        </div>

      </div>
    </section>
    
  

  {% endblock %}

  {% block footer %}
  <footer class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>RSS FeedMixer</span></strong>. All Rights Reserved
    </div>
  </footer><!-- End Footer -->
  {% endblock %}

Url Shortener/url_shortener/templates/stats.html
{% extends "base.html" %}

{% block body %}
  <nav class="navbar navbar-expand-lg navbar-light rounded mb-5 py-4" style="background-color: white; font-size: large; opacity: 1; box-shadow: 0px 0px 15px 0px rgba(1, 41, 112, 0.1);">
      <a class="navbar-brand" href="#"><div class="d-flex align-items-center">
        <a href="/" class="logo d-flex ">
         <div class="icon">
          <i class="fa fa-rss fa-lg mx-1 mt-1" style="color: rgba(12, 12, 105, 0.932);"></i>
         </div>
         
          <span>RSS FeedMixer</span>
        </a>
      </div></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse align-items-center me-5 pe-5" id="navbarsExample09">
        <ul class="navbar-nav mr-auto">
          
        </ul>
    </ul>
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="/add">{{user.first_name}}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/logout">Logout</a>
      </li>
      {% else %}
        <li class="nav-item">
            <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="/register">Register</a>
        </li>
        {% endif %}
    </ul>
      </div>
    </nav>
{% endblock %}

{% block content %}


    <!-- <div class="pagetitle">
      <h1>Blank Page</h1>
    
    </div>End Page Title -->

    <section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h3 class="card-title">Key Features</h3>
              <ul>
                <li>Feature 1</li>
                <li>Feature 2</li>
                <li>Feature 3</li>
              </ul>
            </div>
          </div>

        </div>

      </div>

      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h3 class="card-title" style="font-size: larger;">Your feed mix URLs.</h3>
              <div class="mx-5" style="color:blue;">
                {% for link in links %}
               <div class="mb-2"> Full URL : {{link.original_url}}</div>
               <div class="mb-4"> Short URL : {{url_for('views.redirect_to_url',short_url=link.short_url, _external=True)}}</div>
               <a class="btn btn-primary mb-4" href="{{url_for('views.redirect_to_url',short_url=link.short_url, _external=True)}}">View FeedMix</a>
               {% endfor %}
              </div>
              
            </div>
          </div>

        </div>

      </div>
    </section>
    
  

  {% endblock %}

  {% block footer %}
  <footer class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>RSS FeedMixer</span></strong>. All Rights Reserved
    </div>
  </footer><!-- End Footer -->
  {% endblock %}





{% for link in links %}
Original Url: {{ link.original_url }} <br>
Short Url : {{ link.short_url }} <br>
Visits : {{ link.visits }} <br>
<br>
<br/>
{% endfor %}

Url Shortener/url_shortener/templates/url_add.html
{% extends "base.html" %}
{% block title %} Add Feed {% endblock %}
{% block body %}
  <nav class="navbar navbar-expand-lg navbar-light rounded mb-5 py-4" style="background-color: white; font-size: large; opacity: 1; box-shadow: 0px 0px 15px 0px rgba(1, 41, 112, 0.1);">
      <a class="navbar-brand" href="#"><div class="d-flex align-items-center">
        <a href="/" class="logo d-flex ">
         <div class="icon">
          <i class="fa fa-rss fa-lg mx-1 mt-1" style="color: rgba(12, 12, 105, 0.932);"></i>
         </div>
         
          <span>RSS FeedMixer</span>
        </a>
      </div></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse align-items-center me-5 pe-5" id="navbarsExample09">
        <ul class="navbar-nav mr-auto">
          
        </ul>
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="/add">{{user.first_name}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout">Logout</a>
          </li>
          {% else %}
            <li class="nav-item">
                <a class="nav-link" href="/login">Login</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="/register">Register</a>
            </li>
            {% endif %}
        </ul>
      </div>
    </nav>
{% endblock %}

{% block content %}


    <!-- <div class="pagetitle">
      <h1>Blank Page</h1>
    
    </div>End Page Title -->
    
    {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if messages %} 
    {% for category, message in messages %} 
    {% if category == 'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} 
    {% endfor %} 
    {% endif %} 
    {% endwith %}


    <section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <p class="card-title" style="font-size: 1.5rem;">Add Feeds</p>
              <form method="POST">
                <div class="input-wrapper">
                    <label for="feed">URL</label>
                    <div class="form-group form-row">
                        <div class="col-8">
        
                         <input type="text" name="field[]" value="{{full_url}}" class="form-control input" id="exampleFormControlInput1" placeholder="Add Feed">
                        </div>
                        <div class="col-2">
                         <a href="javascript:void(0);" class="add-input btn btn-outline-primary mx-3" title="Add input"><i class="fa fa-plus"></i></a>
                        </div>
                    </div>
                </div>
                <div class="other-input-wrapper" style="margin-top: 10px;">
                    <label for="limit">Feeds per URL (Optional)</label>
                    <div class="form-group">
                        <input type="text" value="{{n}}" class="form-control" name="limit">
                    </div>
                </div>
                <div>
                    <input type="submit" class="btn btn-outline-primary mt-2" name="cmdsubmit">
                </div>
                
            </form>
            </div>
          </div>

      
        {% if links %}
        <div class="card">
          <div class="card-body">
            <h3 class="card-title" style="font-size: larger;">Your feed mix URLs.</h3>
            <div class="mx-5" style="color:blue;">
              {% for link in links %}
             <div class="mb-2"> Full URL : {{link.original_url}}</div>
             <div class="mb-4"> Short URL : {{url_for('views.redirect_to_url',short_url=link.short_url, _external=True)}}</div>
             <a class="btn btn-primary mb-4" href="{{url_for('views.redirect_to_url',short_url=link.short_url, _external=True)}}">View FeedMix</a>
             {% endfor %}
            </div>
            
          </div>
        </div>

        {% endif %}

    

    </section>

    <script>
        $(document).ready(function(){
            var max_input_fields = 10;
            var add_input = $('.add-input');
            var input_wrapper = $('.input-wrapper');
            var new_input = ' <div class="form-group form-row"><div class="col-8"><input type="text" name="field[]" value="" class="form-control input" id="exampleFormControlInput1" placeholder="Add Feed"> </div><div class="col-2 remove-input"><a href="javascript:void(0);" class=" btn btn-outline-danger mx-3" title="Remove input"><i class="fa fa-minus"></i></a></div></div>';
            var add_input_count = 1; 
            $(add_input).click(function(){
                if(add_input_count < max_input_fields){
                    add_input_count++; 
                    $(input_wrapper).append(new_input); 
                }
            });
            $(input_wrapper).on('click', '.remove-input', function(e){
                e.preventDefault();
                $(this).parent('div').remove();
                add_input_count--;
            });
        });
        </script>

  {% endblock %}
  {% block footer %}
  <footer class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>RSS FeedMixer</span></strong>. All Rights Reserved
    </div>

  </footer><!-- End Footer -->
  {% endblock %}